name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to personal repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add personal https://x-access-token:${{secrets.PERSONAL_REPO_TOKEN}}@github.com/ishaan-awasthi/proxy-tangnt-temp-landing.git
          git push personal HEAD:main --force
